---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  guardrails:
    uses: pr0d1r2/set-and-setting/.github/workflows/guardrails.yml@39772e1f9acb9b1bab654013375d5eb6fd510aae
