---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  guardrails:
    uses: pr0d1r2/set-and-setting/.github/workflows/guardrails.yml@6d0a50c61f98de5c201713c52176c6fa3e1de52b
