---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  guardrails:
    uses: pr0d1r2/set-and-setting/.github/workflows/guardrails.yml@fa89541d7fab4ccfa32a07d5b100c38ead1f9b99
